const ADMIN_EMAILS=['karim.abousamah1@gmail.com','karim.abousamah@gmail.com'];
const STORE_URL='/.netlify/functions/store';
let cloud={nitaProducts:[],nitaOrders:[],nitaCoupons:[],nitaUsersByEmail:{},nitaDiscountUses:{}};
let cart=read('nitaCart',[]), currentUser=read('nitaUser',null), selectedSize=null, appliedCoupon=null;
function read(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function qs(s){return document.querySelector(s)} function qsa(s){return [...document.querySelectorAll(s)]}
function money(n){return '$'+Number(n||0).toFixed(2)} function safe(x){return String(x??'').replace(/[<>&]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[m]))}
async function apiGet(){try{let r=await fetch(STORE_URL,{cache:'no-store'}); if(r.ok)return await r.json()}catch(e){} return null}
async function apiSave(key,value){cloud[key]=value; write(key,value); try{await fetch(STORE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,value})})}catch(e){console.warn(e)} }
async function loadStore(){let remote=await apiGet(); if(remote&&typeof remote==='object'){cloud={...cloud,...remote}; Object.keys(cloud).forEach(k=>write(k,cloud[k]));}else{Object.keys(cloud).forEach(k=>cloud[k]=read(k,cloud[k]));}}
function products(){let saved=cloud.nitaProducts?.length?cloud.nitaProducts:read('nitaProducts',[]); return saved.length?saved:DEFAULT_PRODUCTS}
function product(id){return products().find(p=>String(p.id)===String(id))}
function photo(p,i=0){return p?.photos?.[i]||''}
function imgHtml(p,cls=''){let src=photo(p,0); return src?`<img class="${cls}" src="${src}" alt="${safe(p.name)}">`:''}
function productBg(p){return photo(p,0)?`background-image:url('${photo(p,0)}')`:''}
function effectiveStatus(p){if(p.status==='coming-soon')return 'coming-soon'; if(p.status==='out-of-stock'||Number(p.quantity)<=0)return 'out-of-stock'; if(Number(p.originalQuantity)>0&&Number(p.quantity)<=Number(p.originalQuantity)*0.5)return 'low-stock'; return 'in-stock'}
function statusLabel(p){let s=effectiveStatus(p); return { 'in-stock':'In stock','low-stock':'Low in stock','coming-soon':'Coming soon','out-of-stock':'Out of stock'}[s]}
function statusHtml(p){let s=effectiveStatus(p); return `<span class="status ${s}"><span class="dot"></span>${statusLabel(p)}</span>`}
function priceHtml(p){return p.salePrice?`<div class="price-row"><span class="old">${money(p.price)}</span><span class="sale">${money(p.salePrice)}</span>${statusHtml(p)}</div>`:`<div class="price-row"><span>${money(p.price)}</span>${statusHtml(p)}</div>`}
function header(){let admin=ADMIN_EMAILS.includes(currentUser?.email)?'<a href="admin.html">ADMIN</a>':'';return `<header class="topbar"><nav class="nav"><div class="nav-item"><a href="shop.html">SHOP</a><div class="mega"><div><h4>Shop by category</h4><div class="mega-links"><a href="shop.html?cat=Dresses">Dresses</a><a href="shop.html?cat=Tops">Tops</a><a href="shop.html?cat=Pants">Pants</a><a href="shop.html?cat=Jackets">Jackets</a><a href="shop.html?cat=Accessories">Accessories</a></div></div><div><h4>Shop by edit</h4><div class="mega-links"><a href="shop.html">All products</a><a href="collections.html">New arrivals</a><a href="shop.html?cat=Sale">Price drops</a></div></div></div></div><div class="nav-item"><a href="collections.html">COLLECTIONS</a><div class="mega"><div><h4>Featured</h4><div class="mega-links"><a href="collections.html">Latest edit</a><a href="collections.html">Everyday boutique</a><a href="collections.html">Minimal essentials</a></div></div><div><h4>Occasion</h4><div class="mega-links"><a href="shop.html?cat=Tops">Daywear</a><a href="shop.html?cat=Dresses">Evening</a><a href="shop.html?cat=Accessories">Accessories</a></div></div></div></div><a href="about.html">ABOUT</a></nav><a class="brand" href="index.html"><img src="assets/logo-cropped.png" alt="Nita Style"></a><div class="actions"><button onclick="openPanel('searchPanel')">SEARCH</button><a href="${currentUser?'account.html':'login.html'}">${currentUser?'ACCOUNT':'SIGN IN'}</a>${admin}<button class="cart-btn" onclick="openCart()"><span class="cart-icon"><svg viewBox="0 0 24 24"><path d="M6.5 8.5h11l.8 11H5.7l.8-11Z"/><path d="M9 8.5V7a3 3 0 0 1 6 0v1.5"/></svg></span><span class="cart-count">0</span></button></div></header><div class="panel" id="searchPanel"><div class="drawer"><button class="close" onclick="closePanel('searchPanel')">×</button><h2>Search</h2><input class="field" id="searchInput" placeholder="Search products" oninput="renderSearch()"><div id="searchResults"></div></div></div><div class="panel" id="cartPanel"><div class="drawer"><button class="close" onclick="closePanel('cartPanel')">×</button><h2>Your cart</h2><div id="cartItems"></div><a id="drawerCheckout" class="btn" href="checkout.html" style="width:100%;margin-top:20px">CHECKOUT</a></div></div><div class="panel" id="quickPanel"><div class="modal-card"><button class="close" onclick="closePanel('quickPanel')" style="position:absolute;right:14px;top:14px;z-index:2">×</button><div class="modal-img" id="quickImg"></div><div class="modal-info" id="quickInfo"></div></div></div>`}
function footer(){return `<footer class="footer"><div><img class="footer-logo-img" src="assets/logo-cropped.png"><p class="muted">Founded by Nicole and Tania, Nita Style curates Italian-made pieces for women who value clean silhouettes and effortless everyday elegance.</p></div><div><h4>Shop</h4><a href="shop.html">All products</a><a href="collections.html">Collections</a><a href="cart.html">Cart</a><a href="checkout.html">Checkout</a></div><div><h4>Support</h4><a href="contact.html">Contact</a><a href="about.html">About</a><a href="checkout.html">Cash on delivery</a><a href="checkout.html">Online payment coming soon</a></div><div><h4>Join the list</h4><p class="muted">Receive the first-order code and new drop updates.</p><input class="field" placeholder="Email address"><button class="btn" style="margin-top:10px">SIGN UP</button></div></footer><div class="copyright"><span>© 2026 Nita Style. All rights reserved.</span><span>Privacy Policy · Terms · Shipping</span></div>`}
async function init(){await loadStore(); cart=read('nitaCart',[]); currentUser=read('nitaUser',null); document.body.insertAdjacentHTML('afterbegin',header()); if(!document.querySelector('.no-footer'))document.body.insertAdjacentHTML('beforeend',footer()); updateCartCount(); renderCart(); document.body.classList.add('ready');}
function openPanel(id){qs('#'+id)?.classList.add('open');document.body.style.overflow='hidden'; if(id==='searchPanel')setTimeout(()=>qs('#searchInput')?.focus(),50)}
function closePanel(id){qs('#'+id)?.classList.remove('open');document.body.style.overflow=''}
function openCart(){renderCart();openPanel('cartPanel')}
function updateCartCount(){qsa('.cart-count').forEach(e=>e.textContent=cart.reduce((s,i)=>s+Number(i.qty||0),0))}
function saveCart(){write('nitaCart',cart);updateCartCount();renderCart()}
function renderSearch(){let q=qs('#searchInput')?.value.toLowerCase()||''; let list=products().filter(p=>!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)); qs('#searchResults').innerHTML=list.map(p=>`<a class="cart-item" href="product.html?id=${p.id}"><div class="placeholder" style="${productBg(p)};background-size:cover;background-position:center"></div><div><b>${safe(p.name)}</b><p class="muted">${safe(p.category)} · ${money(p.salePrice||p.price)}</p></div></a>`).join('')}
function productCard(p){let badge=p.salePrice?'<span class="badge">PRICE DROP</span>':'';return `<div class="product-card"><div class="product-media placeholder" style="${productBg(p)};background-size:cover;background-position:center"><button class="btn light quick-btn" onclick="event.preventDefault();event.stopPropagation();quickView('${p.id}')">QUICK VIEW</button>${badge}</div><a href="product.html?id=${p.id}"><h3>${safe(p.name)}</h3>${priceHtml(p)}</a></div>`}
function renderMarquee(id,list){let el=qs('#'+id); if(!el)return; let items=list.length?list:products().slice(0,4); let html=[...items,...items].map(productCard).join(''); el.innerHTML=`<div class="marquee-viewport"><div class="marquee-track">${html}</div></div>`}
function homePage(){let ps=products(); renderMarquee('trending',ps.filter(p=>(p.homeSection||'trending')==='trending')); renderMarquee('newArrivals',ps.filter(p=>p.homeSection==='new'));}
function renderGrid(el,list){qs(el).innerHTML=list.map(productCard).join('')}
function shopPage(){let url=new URL(location.href);let cat=url.searchParams.get('cat')||'All'; qs('#filter')&&(qs('#filter').value=cat); let list=products().filter(p=>cat==='All'||p.category===cat); renderGrid('#products',list)}
function selectSize(s){selectedSize=s;qsa('.size-btn').forEach(b=>b.classList.toggle('active',b.dataset.size===s))}
function addToCart(id,size){let p=product(id); if(!p)return; if(effectiveStatus(p)!=='in-stock'&&effectiveStatus(p)!=='low-stock'){toast('This item is not available yet.');return} size=size||selectedSize||p.sizes?.[0]||'One size'; if((p.outOfStockSizes||[]).includes(size)){toast('This size is out of stock.');return} let item=cart.find(i=>String(i.id)===String(id)&&i.size===size); if(item)item.qty++; else cart.push({id:String(id),size,qty:1}); saveCart(); toast('Added to cart')}
function renderCart(){let box=qs('#cartItems'); if(!box)return; if(!cart.length){box.innerHTML='<p class="muted">Your cart is empty.</p>'; qs('#drawerCheckout')?.classList.add('disabled'); qs('#drawerCheckout')?.setAttribute('onclick','return false'); return} qs('#drawerCheckout')?.classList.remove('disabled'); qs('#drawerCheckout')?.removeAttribute('onclick'); let total=0; box.innerHTML=cart.map((i,idx)=>{let p=product(i.id); if(!p)return''; let unit=p.salePrice||p.price; total+=unit*i.qty; return `<div class="cart-item"><div class="placeholder" style="${productBg(p)};background-size:cover;background-position:center"></div><div><b>${safe(p.name)}</b><p class="muted">${safe(i.size)}</p><div class="qty"><button onclick="changeQty(${idx},-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${idx},1)">+</button></div></div><div><b>${money(unit*i.qty)}</b><br><button onclick="cart.splice(${idx},1);saveCart()">×</button></div></div>`}).join('')+`<h3>Total ${money(total)}</h3>`}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);saveCart()}
function quickView(id){let p=product(id); if(!p)return; qs('#quickImg').innerHTML=imgHtml(p)||'<div class="placeholder" style="width:100%;height:100%"></div>'; qs('#quickInfo').innerHTML=`<p class="muted">${safe(p.category)}</p><h2>${safe(p.name)}</h2>${priceHtml(p)}<p>${safe(p.description||'A carefully selected Italian-made piece.')}</p>${sizePicker(p)}<button class="btn ${['coming-soon','out-of-stock'].includes(effectiveStatus(p))?'disabled':''}" onclick="addToCart('${p.id}')">${['coming-soon','out-of-stock'].includes(effectiveStatus(p))?'NOTIFY ME':'ADD TO CART'}</button><p><a href="product.html?id=${p.id}">View full product</a></p>`;openPanel('quickPanel')}
function sizePicker(p){return `<div class="size-grid">${(p.sizes||['One size']).map(s=>`<button class="size-btn ${(p.outOfStockSizes||[]).includes(s)?'oos':''}" data-size="${safe(s)}" ${(p.outOfStockSizes||[]).includes(s)?'disabled':''} onclick="selectSize('${safe(s)}')">${safe(s)}</button>`).join('')}</div>`}
function productPage(){let p=product(new URL(location.href).searchParams.get('id')); if(!p){qs('#detail').innerHTML='<h1>Product not found</h1>';return} selectedSize=(p.sizes||[]).find(s=>!(p.outOfStockSizes||[]).includes(s))||null; qs('#detail').innerHTML=`<div><div class="gallery-main">${imgHtml(p)||'<div class="placeholder" style="width:100%;height:100%"></div>'}</div><div class="thumbs">${(p.photos||[]).map(src=>`<img src="${src}" onclick="qs('.gallery-main').innerHTML='<img src=&quot;${src}&quot;>'">`).join('')}</div></div><div class="detail"><p class="muted">${safe(p.category)}</p><h1>${safe(p.name)}</h1>${priceHtml(p)}<p>${safe(p.description)}</p>${sizePicker(p)}<button class="btn ${['coming-soon','out-of-stock'].includes(effectiveStatus(p))?'disabled':''}" onclick="addToCart('${p.id}')">${['coming-soon','out-of-stock'].includes(effectiveStatus(p))?'NOTIFY ME':'ADD TO CART'}</button><p class="muted">Cash on delivery available. Online payment coming soon.</p></div>`}
function fullCart(){let el=qs('#fullCart'); renderCart(); el.innerHTML=qs('#cartItems').innerHTML+`<a class="btn ${cart.length?'':'disabled'}" ${cart.length?'href="checkout.html"':'onclick="return false"'}>CHECKOUT</a>`}
function subtotal(){return cart.reduce((s,i)=>{let p=product(i.id);return s+(Number(p?.salePrice||p?.price||0)*Number(i.qty||0))},0)}
function shipping(){return cart.length?7:0}
function validCoupon(code){let c=(cloud.nitaCoupons||[]).find(x=>String(x.code).toUpperCase()===String(code).toUpperCase()); if(!c)return null; let now=new Date(); if(c.start&&new Date(c.start)>now)return null; if(c.end&&new Date(c.end)<now)return null; return c}
function applyCoupon(){let code=qs('#coupon')?.value.trim(); let c=validCoupon(code); if(!c){appliedCoupon=null;qs('#couponMsg').textContent='Coupon code is expired or not applicable.';summary();return} appliedCoupon=c; qs('#couponMsg').textContent='Coupon applied.'; summary()}
function savedAddresses(){let u=cloud.nitaUsersByEmail?.[currentUser?.email]||read('nitaUsersByEmail',{})[currentUser?.email]||{}; return u.addresses||[]}
function checkoutPage(){if(!cart.length){qs('#checkoutRoot').innerHTML='<main class="page"><h1>Your cart is empty</h1><a class="btn" href="shop.html">SHOP NOW</a></main>';return} let addresses=savedAddresses(); qs('#checkoutRoot').innerHTML=`<div class="checkout-layout"><div class="checkout-left"><h2>Contact</h2><input class="field" id="coEmail" placeholder="Email or mobile phone number" value="${safe(currentUser?.email||'')}"><label><input type="checkbox" checked> Email me with news and offers</label><h2>Delivery</h2><div id="savedAddressArea">${addresses.length?renderSavedAddresses(addresses):''}</div><button class="btn light" type="button" onclick="showAddressForm()">ADD NEW LOCATION</button><form id="checkoutForm" class="${addresses.length?'hide':''}" onsubmit="event.preventDefault();placeOrder()">${addressForm()}<label><input id="saveAddr" type="checkbox"> Save this information for next time</label></form><h2>Shipping method</h2><div class="shipping-box selected"><b>Aramex delivery across Lebanon</b><span style="float:right">$7.00</span><p class="muted">2–3 business days · Orders under $150</p></div><h2>Payment</h2><div class="payment-box"><b>Credit card</b><span class="muted" style="float:right">Coming soon</span></div><div class="payment-box active"><b>Cash on Delivery (COD)</b><p class="muted">Cash on delivery is currently active in Lebanon.</p></div><button class="btn" onclick="placeOrder()" style="width:100%;margin-top:22px">COMPLETE ORDER</button></div><div class="checkout-right"><h2>Order summary</h2><div id="summary"></div><div class="coupon-apply"><input class="field" id="coupon" placeholder="Discount code or gift card"><button class="btn light" onclick="applyCoupon()">Apply</button></div><p id="couponMsg" class="muted"></p></div></div>`; summary()}
function renderSavedAddresses(arr){return `<div class="address-list">${arr.map((a,i)=>`<div class="address-card ${i===0?'selected':''}" data-idx="${i}"><label><input type="radio" name="addr" value="${i}" ${i===0?'checked':''}> <b onclick="toggleAddr(${i});return false">${safe(a.label||'Saved address')}</b></label><div class="addr-details ${i===0?'':'hide'}"><p>${safe(a.address||a.street||'')} ${safe(a.building||'')}, ${safe(a.city||'')}</p><p class="muted">${safe(a.phone||'')}</p></div></div>`).join('')}</div>`}
function toggleAddr(i){qsa('.addr-details').forEach((e,n)=>{if(n===i)e.classList.toggle('hide')})}
function showAddressForm(){qs('#checkoutForm')?.classList.remove('hide')}
function addressForm(){return `<div class="form-grid" style="margin:14px 0"><input class="field full" name="label" placeholder="Address name, e.g. Home or Office"><input class="field" name="first" placeholder="First name" required><input class="field" name="last" placeholder="Last name" required><input class="field full" name="address" placeholder="Address" required><input class="field full" name="apartment" placeholder="Apartment, suite, etc. (optional)"><input class="field" name="city" placeholder="City" required><input class="field" name="postal" placeholder="Postal code (optional)"><input class="field full" name="phone" placeholder="Phone" required></div>`}
function summary(){let sub=subtotal(), ship=shipping(), disc=appliedCoupon?sub*(Number(appliedCoupon.percent||0)/100):0; qs('#summary')&&(qs('#summary').innerHTML=cart.map(i=>{let p=product(i.id);return `<div class="summary-line"><span>${safe(p?.name)} × ${i.qty}</span><b>${money((p?.salePrice||p?.price||0)*i.qty)}</b></div>`}).join('')+`<hr><div class="summary-line"><span>Subtotal</span><b>${money(sub)}</b></div><div class="summary-line"><span>Shipping</span><b>${money(ship)}</b></div>${disc?`<div class="summary-line"><span>Discount</span><b>-${money(disc)}</b></div>`:''}<h2 class="summary-line"><span>Total</span><b>${money(sub+ship-disc)}</b></h2>`)}
async function placeOrder(){if(!cart.length){toast('Your cart is empty.');return} let f=qs('#checkoutForm'); let address={}; if(f&&!f.classList.contains('hide')){if(!f.reportValidity())return; address=Object.fromEntries(new FormData(f).entries()); if(qs('#saveAddr')?.checked&&currentUser?.email){let users=cloud.nitaUsersByEmail||{}; let u=users[currentUser.email]||{email:currentUser.email,addresses:[]}; u.addresses=u.addresses||[]; u.addresses.push(address); users[currentUser.email]=u; await apiSave('nitaUsersByEmail',users)}} else {let arr=savedAddresses(); let idx=Number(qs('input[name="addr"]:checked')?.value||0); address=arr[idx]||{}} let sub=subtotal(), ship=shipping(), disc=appliedCoupon?sub*(Number(appliedCoupon.percent||0)/100):0; let orders=cloud.nitaOrders||[]; let order={id:'NS'+Date.now(),date:new Date().toLocaleString(),email:currentUser?.email||qs('#coEmail')?.value||'',customer:(address.first||'')+' '+(address.last||''),phone:address.phone,address,payment:'Cash on Delivery',status:'Order submitted',items:cart,total:sub+ship-disc}; orders.push(order); await apiSave('nitaOrders',orders); let ps=products(); cart.forEach(i=>{let p=ps.find(x=>String(x.id)===String(i.id)); if(p){p.quantity=Math.max(0,Number(p.quantity||0)-Number(i.qty||0)); if(p.quantity===0)p.status='out-of-stock'}}); await apiSave('nitaProducts',ps); cart=[]; saveCart(); location.href='order-success.html'}
function loginPage(){qs('#loginRoot').innerHTML=`<img src="assets/logo-cropped.png" style="width:280px"><p class="muted brand-font">Customer account</p><h1>Sign in or create your account</h1><p class="muted">Save your address, track your orders, and receive your first-order code.</p><div class="auth-tabs"><button id="tabIn" class="active" onclick="setAuth('in')">SIGN IN</button><button id="tabUp" onclick="setAuth('up')">SIGN UP</button></div><div class="card"><input id="authEmail" class="field" placeholder="Email address"><input id="authFirst" class="field" placeholder="First name"><input id="authLast" class="field" placeholder="Last name"><input id="authPhone" class="field" placeholder="Phone number"><button class="btn" onclick="submitAuth()">CONTINUE</button></div>`}
function setAuth(t){qs('#tabIn').classList.toggle('active',t==='in');qs('#tabUp').classList.toggle('active',t==='up')}
async function submitAuth(){let email=qs('#authEmail').value.trim().toLowerCase(); if(!email)return toast('Enter your email'); let users=cloud.nitaUsersByEmail||{}; users[email]={...(users[email]||{}),email,first:qs('#authFirst').value,last:qs('#authLast').value,phone:qs('#authPhone').value,addresses:(users[email]?.addresses||[])}; await apiSave('nitaUsersByEmail',users); currentUser={email}; write('nitaUser',currentUser); location.href='index.html'}
function accountPage(){if(!currentUser){location.href='login.html';return} let u=(cloud.nitaUsersByEmail||{})[currentUser.email]||{email:currentUser.email,addresses:[]}; let orders=(cloud.nitaOrders||[]).filter(o=>o.email===currentUser.email); qs('#accountRoot').innerHTML=`<h1>Welcome ${safe(u.first||'')}</h1><p class="muted">Manage your profile, delivery addresses, and orders.</p><div class="grid" style="grid-template-columns:1fr 1fr"><div class="card"><h2>Personal information</h2><input class="field" id="accFirst" value="${safe(u.first||'')}" placeholder="First name"><input class="field" id="accLast" value="${safe(u.last||'')}" placeholder="Last name"><input class="field" disabled value="${safe(u.email)}"><input class="field" id="accPhone" value="${safe(u.phone||'')}" placeholder="Phone"><button class="btn" onclick="saveAccount()">SAVE DETAILS</button></div><div class="card"><h2>Saved delivery addresses</h2>${(u.addresses||[]).map(a=>`<div class="address-card"><b>${safe(a.label||'Saved address')}</b><p>${safe(a.address||'')} ${safe(a.city||'')}</p></div>`).join('')||'<p class="muted">No saved addresses yet.</p>'}</div></div><section class="card" style="margin-top:30px"><h2>Ongoing orders</h2>${orders.length?orders.map(orderCard).join(''):'<p class="muted">No orders yet.</p>'}</section><section class="account-control" style="margin-top:30px"><h2>Account control</h2><button class="btn outline-danger" onclick="localStorage.removeItem('nitaUser');location.href='index.html'">LOG OUT</button> <button class="btn danger" onclick="deleteAccount()">DELETE ACCOUNT</button></section>`}
function orderCard(o){let steps=['Order submitted','Confirmed','Packing','Out for delivery','Delivered']; let idx=Math.max(0,steps.findIndex(s=>s.toLowerCase()===String(o.status).toLowerCase())); return `<div class="card" style="margin:18px 0"><b>${safe(o.id)}</b><p class="muted">${safe(o.date)} · ${safe(o.payment)}</p><b>${money(o.total)}</b><div class="order-roadmap">${steps.map((s,i)=>`<div class="road-step ${i<=idx?'done':''}">${s}</div>`).join('')}</div><p class="muted">${(o.items||[]).map(i=>safe(i.id)+' × '+i.qty).join(', ')}</p></div>`}
async function saveAccount(){let users=cloud.nitaUsersByEmail||{}; let u=users[currentUser.email]||{email:currentUser.email,addresses:[]}; u.first=qs('#accFirst').value;u.last=qs('#accLast').value;u.phone=qs('#accPhone').value;users[currentUser.email]=u; await apiSave('nitaUsersByEmail',users);toast('Saved')}
async function deleteAccount(){if(!confirm('Delete account permanently?'))return; let users=cloud.nitaUsersByEmail||{}; delete users[currentUser.email]; await apiSave('nitaUsersByEmail',users); localStorage.removeItem('nitaUser'); location.href='index.html'}
function requireAdmin(){if(!ADMIN_EMAILS.includes(currentUser?.email)){qs('main').innerHTML='<h1>Admin access</h1><a class="btn" href="login.html">SIGN IN</a>';return false}return true}
function adminPage(){if(!requireAdmin())return; let ed=qs('#productEditor'); if(ed)ed.innerHTML=adminForm(); renderAdminProducts(); renderAdminOrders(); renderAdminUsers()}
function sizeChecks(name,selected=[]){return ['XS','S','M','L','XL','One size'].map(s=>`<label><input type="checkbox" name="${name}" value="${s}" ${selected.includes(s)?'checked':''}> ${s}</label>`).join(' ')}
function collectChecks(name){return qsa(`input[name="${name}"]:checked`).map(x=>x.value)}
function adminForm(p={}){return `<div class="form-grid"><input id="pname" class="field" placeholder="Product name" value="${safe(p.name||'')}"><input id="pprice" class="field" type="number" placeholder="Price" value="${safe(p.price||'')}"><input id="psale" class="field" type="number" placeholder="Sale price" value="${safe(p.salePrice||'')}"><input id="pqty" class="field" type="number" placeholder="Quantity" value="${safe(p.quantity||'')}"><select id="pcat" class="field"><option>Dresses</option><option>Tops</option><option>Pants</option><option>Jackets</option><option>Accessories</option></select><select id="phome" class="field"><option value="trending">Trending Now</option><option value="new">New Arrivals</option></select><select id="pstatus" class="field"><option value="in-stock">In stock</option><option value="coming-soon">Coming soon</option><option value="out-of-stock">Out of stock</option></select><input id="pcolor" class="field" placeholder="Color" value="${safe(p.color||'')}"><textarea id="pdesc" class="field full" placeholder="Description">${safe(p.description||'')}</textarea><div class="full"><label>Photos</label><input id="pphotos" type="file" multiple accept="image/*"></div><div class="full"><label>Available sizes</label><p>${sizeChecks('sizes',p.sizes||['S','M','L'])}</p></div><div class="full"><label>Out-of-stock sizes</label><p>${sizeChecks('oos',p.outOfStockSizes||[])}</p></div></div>`}
async function fileToData(f){return new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})}
async function productFromForm(old={}){let files=[...(qs('#pphotos')?.files||[])]; let photos=files.length?await Promise.all(files.map(fileToData)):(old.photos||[]); let qty=Number(qs('#pqty').value||old.quantity||0); return {...old,id:old.id||('p'+Date.now()),name:qs('#pname').value,price:Number(qs('#pprice').value),salePrice:qs('#psale').value?Number(qs('#psale').value):null,quantity:qty,originalQuantity:old.originalQuantity||qty,category:qs('#pcat').value,homeSection:qs('#phome').value,status:qs('#pstatus').value,color:qs('#pcolor').value,description:qs('#pdesc').value,photos,sizes:collectChecks('sizes'),outOfStockSizes:collectChecks('oos')}}
function renderAdminProducts(){let box=qs('#adminProducts'); if(!box)return; box.innerHTML=products().map(p=>`<div class="admin-list-item"><div class="placeholder" style="${productBg(p)};height:80px;background-size:cover;background-position:center"></div><div><b>${safe(p.name)}</b><p class="muted">${safe(p.category)} · ${money(p.salePrice||p.price)} · Qty ${p.quantity}</p>${statusHtml(p)}</div><button class="btn light" onclick="editProduct('${p.id}')">EDIT LISTING</button><button class="btn light remove" onclick="removeProduct('${p.id}')">REMOVE</button></div>`).join('')}
async function addProductAdmin(){let ps=products(); ps.push(await productFromForm()); await apiSave('nitaProducts',ps); renderAdminProducts(); toast('Product saved')}
function editProduct(id){let p=product(id); qs('#productEditor').innerHTML=adminForm(p)+`<button class="btn" onclick="saveProduct('${id}')">SAVE UPDATE</button>`; qs('#pcat').value=p.category;qs('#phome').value=p.homeSection||'trending';qs('#pstatus').value=p.status||'in-stock'; window.scrollTo(0,0)}
async function saveProduct(id){let ps=products(); let idx=ps.findIndex(p=>String(p.id)===String(id)); ps[idx]=await productFromForm(ps[idx]); await apiSave('nitaProducts',ps); qs('#productEditor').innerHTML=adminForm()+`<button class="btn" onclick="addProductAdmin()">ADD PRODUCT</button>`; renderAdminProducts(); toast('Updated')}
async function removeProduct(id){if(!confirm('Remove this product?'))return; await apiSave('nitaProducts',products().filter(p=>String(p.id)!==String(id))); renderAdminProducts(); toast('Removed')}
function renderAdminOrders(){let box=qs('#adminOrders'); if(!box)return; let orders=cloud.nitaOrders||[]; box.innerHTML=orders.length?orders.map((o,i)=>`<div class="card"><b>${safe(o.id)}</b><p>${safe(o.customer)} · ${money(o.total)}</p><select onchange="updateOrder(${i},this.value)"><option>${safe(o.status)}</option><option>Confirmed</option><option>Packing</option><option>Out for delivery</option><option>Delivered</option><option>Cancelled</option></select></div>`).join(''):'<p class="muted">No orders yet.</p>'}
async function updateOrder(i,v){if(!confirm('Confirm order status update?'))return; let orders=cloud.nitaOrders||[]; orders[i].status=v; await apiSave('nitaOrders',orders);renderAdminOrders()}
function renderAdminUsers(){let box=qs('#adminUsers'); if(!box)return; let users=Object.values(cloud.nitaUsersByEmail||{}); box.innerHTML=users.map(u=>`<div class="card"><b>${safe(u.email)}</b><p>${safe(u.first||'')} ${safe(u.last||'')} · ${safe(u.phone||'')}</p></div>`).join('')||'<p class="muted">No customers yet.</p>'}
function toast(t){let e=qs('#toast')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'toast',className:'toast'}));e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',1900)}
