/* Nita Style clean unified controller - June 2026 */
const NITA_OWNER_EMAILS = ['karim.abousamah1@gmail.com','karim.abousamah@gmail.com'];
const DELIVERY_FEE = 7;
const FREE_DELIVERY_MIN = 150;
const ORDER_STEPS = ['Order submitted','Confirmed','Packing','Out for delivery','Delivered'];
const ADMIN_CATEGORIES = ['Dresses','Tops','Pants','Jackets','Accessories'];
const ADMIN_COLLECTIONS = ['Trending Now','New Arrivals','Everyday Edit','Minimal Essentials','Evening Pieces','Accessories','Price Drops'];
const PRODUCT_SIZES = ['XS','S','M','L','XL','One Size'];

let cart = [];
let currentUser = null;
let verificationDraft = null;

const $ = (q,root=document)=>root.querySelector(q);
const $$ = (q,root=document)=>Array.from(root.querySelectorAll(q));
const safe = v => String(v ?? '').replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const money = n => '$' + Number(n || 0).toFixed(2);
const normEmail = e => String(e || '').trim().toLowerCase();
const getJSON = (k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null') ?? f}catch{return f}};
const setJSON = (k,v)=>{localStorage.setItem(k,JSON.stringify(v)); return v};

function products(){ return typeof getProducts === 'function' ? getProducts() : (window.defaultProducts || []); }
async function cloudSave(key,value){
  try{ if(typeof saveSharedKeyNow==='function') return await saveSharedKeyNow(key,value); }
  catch(e){ console.warn('Cloud save failed',key,e); }
  return false;
}
async function refreshCloud(){ try{ if(typeof loadSharedStore==='function') await loadSharedStore(); }catch(e){ console.warn('Cloud load skipped', e); } }

function getUsers(){ return getJSON('nitaUsersByEmail',{}); }
async function saveUsers(users){ setJSON('nitaUsersByEmail',users); await cloudSave('nitaUsersByEmail',users); }
function getOrders(){ return getJSON('nitaOrders',[]); }
async function saveOrders(orders){ setJSON('nitaOrders',orders); await cloudSave('nitaOrders',orders); }
function getCoupons(){ return getJSON('nitaCoupons',[]); }
async function saveCoupons(coupons){ setJSON('nitaCoupons',coupons); await cloudSave('nitaCoupons',coupons); }
function getDiscountUses(){ return getJSON('nitaDiscountUses',{}); }
async function saveDiscountUses(uses){ setJSON('nitaDiscountUses',uses); await cloudSave('nitaDiscountUses',uses); }
function getAdminEmails(){
  const stored = getJSON('nitaAdminEmails',[]).map(normEmail).filter(Boolean);
  return Array.from(new Set([...NITA_OWNER_EMAILS.map(normEmail), ...stored]));
}
async function saveAdminEmails(list){ const next=Array.from(new Set([...NITA_OWNER_EMAILS.map(normEmail), ...list.map(normEmail).filter(Boolean)])); setJSON('nitaAdminEmails',next); await cloudSave('nitaAdminEmails',next); }
function isAdmin(email=currentUser?.email){ return getAdminEmails().includes(normEmail(email)); }
function saveSession(user){ currentUser=user; if(user) localStorage.setItem('nitaUser',JSON.stringify(user)); else localStorage.removeItem('nitaUser'); updateHeaderCounts(); }
function loadSession(){ currentUser=getJSON('nitaUser',null); return currentUser; }
function saveCart(){ setJSON('nitaCart',cart); updateCartCount(); }
function loadCart(){ cart=getJSON('nitaCart',[]); return cart; }

function productMainImage(p){ return (p?.photos && p.photos[Number(p.mainPhotoIndex||0)]) || p?.img || 'linear-gradient(135deg,#fafafa,#ddd)'; }
function productPrice(p){ return Number(p?.salePrice || p?.price || 0); }
function productOriginalPrice(p){ return Number(p?.price || 0); }
function productStatus(p){
  if(p.status === 'coming-soon') return 'coming-soon';
  if(p.status === 'out-of-stock' || Number(p.quantity||0) === 0) return 'out-of-stock';
  const initial = Number(p.initialQuantity || p.quantity || 0);
  const qty = Number(p.quantity || 0);
  if(initial > 0 && qty > 0 && qty <= initial * 0.5) return 'low-stock';
  return 'in-stock';
}
function statusLabel(status){ return ({'in-stock':'In stock','low-stock':'Low in stock','coming-soon':'Coming soon','out-of-stock':'Out of stock'})[status] || 'In stock'; }
function statusClass(status){ return `status ${status}`; }
function sizesOf(p){ return Array.isArray(p.sizes)&&p.sizes.length ? p.sizes : ['One Size']; }
function outSizesOf(p){ return Array.isArray(p.outOfStockSizes) ? p.outOfStockSizes : []; }

function init(){
  return (async()=>{
    await refreshCloud();
    loadSession(); loadCart();
    document.body.insertAdjacentHTML('afterbegin', headerHTML() + quickViewHTML());
    document.body.classList.add('nita-ready');
    updateCartCount(); updateHeaderCounts(); renderCartPanel();
    if(!document.querySelector('.site-footer') && !location.pathname.endsWith('admin.html')) document.body.insertAdjacentHTML('beforeend', siteFooter());
    if(location.pathname.endsWith('/') || location.pathname.endsWith('index.html') || location.pathname==='/') renderHomeSections();
    return true;
  })();
}

function headerHTML(){
  const adminLink = isAdmin() ? '<a href="admin.html">ADMIN</a>' : '';
  return `<header class="topbar"><nav class="nav"><div class="nav-item"><a href="shop.html">SHOP</a><div class="mega compact-mega"><div class="mega-block"><h4>SHOP BY CATEGORY</h4><div class="mega-links">${ADMIN_CATEGORIES.map(c=>`<a href="shop.html?cat=${encodeURIComponent(c)}">${c}</a>`).join('')}</div></div><div class="mega-block"><h4>SHOP BY EDIT</h4><div class="mega-links"><a href="collections.html">New Arrivals</a><a href="shop.html?cat=Essentials">Essentials</a><a href="shop.html?cat=Evening">Evening Pieces</a><a href="shop.html?cat=Sale">Price Drops</a></div></div></div></div><div class="nav-item"><a href="collections.html">COLLECTIONS</a></div><a href="about.html">ABOUT</a></nav><a class="brand" href="index.html"><img src="assets/logo-cropped.png" alt="Nita Style"></a><div class="actions"><button onclick="openSearch()" class="nav-text-btn">SEARCH</button><a href="${currentUser?'account.html':'login.html'}">${currentUser?'ACCOUNT':'SIGN IN'}</a>${adminLink}<a class="liked-nav-link" href="liked.html" aria-label="Liked items" title="Liked items"><span class="heart-nav">♡</span><span class="liked-count">0</span></a><button class="cart-icon-btn" onclick="openCart()" aria-label="Cart"><span class="cart-icon">▢</span><span class="cart-count">0</span></button></div></header><aside class="search-panel" id="searchPanel"><button class="close" onclick="closeSearch()">×</button><h2>Search</h2><input id="searchInput" class="field" placeholder="Search products" oninput="renderSearch()"><div id="searchResults"></div></aside><aside class="cart-panel" id="cartPanel"><button class="close" onclick="closeCart()">×</button><h2>Your Cart</h2><div id="cartItems"></div></aside>`;
}
function siteFooter(){return `<footer class="footer site-footer"><div><img class="footer-logo-img" src="assets/logo-cropped.png" alt="Nita Style"><p class="muted">Founded by Nicole and Tania, Nita Style curates Italian-made pieces for women who value clean silhouettes, refined textures, and effortless everyday elegance.</p></div><div><h4>Shop</h4><a href="shop.html">All products</a><a href="collections.html">Collections</a><a href="cart.html">Cart</a><a href="checkout.html">Checkout</a></div><div><h4>Support</h4><a href="contact.html">Contact</a><a href="about.html">About</a><a href="checkout.html">Cash on delivery</a><a href="checkout.html">Online payment coming soon</a></div><div><h4>Join the list</h4><p class="muted">Receive the first-order code and new drop updates.</p><div class="footer-newsletter"><input placeholder="Email address"><button> SIGN UP </button></div></div></footer><div class="copyright site-footer"><span>© 2026 Nita Style. All rights reserved.</span><span>Privacy Policy · Terms · Shipping</span></div>`}
function updateCartCount(){ document.querySelectorAll('.cart-count').forEach(e=>e.textContent=cart.reduce((s,i)=>s+Number(i.qty||0),0)); }
function updateHeaderCounts(){ const n=getLikedIds().length; document.querySelectorAll('.liked-count').forEach(e=>e.textContent=n); }
function openSearch(){ $('#searchPanel')?.classList.add('open'); document.body.classList.add('panel-open'); renderSearch(); setTimeout(()=>$('#searchInput')?.focus(),100); }
function closeSearch(){ $('#searchPanel')?.classList.remove('open'); document.body.classList.remove('panel-open'); }
function openCart(){ renderCartPanel(); $('#cartPanel')?.classList.add('open'); document.body.classList.add('panel-open'); }
function closeCart(){ $('#cartPanel')?.classList.remove('open'); document.body.classList.remove('panel-open'); }
function toast(msg){ let t=$('#toast'); if(!t){t=document.createElement('div'); t.id='toast'; t.className='toast'; document.body.appendChild(t);} t.textContent=msg; t.style.display='block'; clearTimeout(t._timer); t._timer=setTimeout(()=>t.style.display='none',2300); }

function renderSearch(){ const q=($('#searchInput')?.value||'').toLowerCase(); const out=products().filter(p=>!q || p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q)); const box=$('#searchResults'); if(box) box.innerHTML=out.map(p=>`<a class="search-row" href="product.html?id=${p.id}"><span class="mini-img" style="${imageStyle(productMainImage(p))}"></span><span><b>${safe(p.name)}</b><br><small>${safe(p.category)} · ${money(productPrice(p))}</small></span></a>`).join('') || '<p class="muted">No results.</p>'; }

function imageStyle(img){ return img && img.startsWith('data:') ? `background-image:url(${img});background-size:cover;background-position:center` : `background:${img||'linear-gradient(135deg,#fafafa,#ddd)'}`; }
function isLiked(id){ return getLikedIds().includes(String(id)); }
function getLikedIds(){ const email=normEmail(currentUser?.email); if(email){ const users=getUsers(); return (users[email]?.liked||[]).map(String); } return getJSON('nitaLikedGuest',[]).map(String); }
async function setLikedIds(ids){ ids=Array.from(new Set(ids.map(String))); const email=normEmail(currentUser?.email); if(email){ const users=getUsers(); users[email]=users[email]||{email}; users[email].liked=ids; await saveUsers(users); } else setJSON('nitaLikedGuest',ids); updateHeaderCounts(); }
async function toggleLike(id, ev){ if(ev){ev.preventDefault(); ev.stopPropagation();} const ids=getLikedIds(); const s=String(id); const liked=ids.includes(s); const next=liked ? ids.filter(x=>x!==s) : [...ids,s]; await setLikedIds(next); toast(liked?'Removed from liked items':'Saved to liked items'); updateLikeButtons(); if(location.pathname.endsWith('liked.html')) renderLikedPage(); }
function updateLikeButtons(){ document.querySelectorAll('[data-like-id]').forEach(btn=>{ const liked=isLiked(btn.dataset.likeId); btn.classList.toggle('liked',liked); btn.innerHTML=liked?'♥':'♡'; btn.title=liked?'Remove from liked items':'Add to liked items'; }); }
function likeButtonHTML(id, extra=''){ return `<button type="button" class="like-btn ${extra}" data-like-id="${id}" onclick="toggleLike('${id}',event)" aria-label="Like product">${isLiked(id)?'♥':'♡'}</button>`; }

function productCard(p){
  const sale = p.salePrice && Number(p.salePrice)<Number(p.price);
  const status=productStatus(p);
  return `<article class="product"><div class="product-card-top"><a class="product-hit" href="product.html?id=${p.id}"><div class="product-img" style="${imageStyle(productMainImage(p))}">${sale?'<span class="sale-badge">PRICE DROP</span>':''}</div></a>${likeButtonHTML(p.id,'card-like')}</div><a class="product-hit" href="product.html?id=${p.id}"><h3>${safe(p.name)}</h3><p class="price-line">${sale?`<span class="muted old-price">${money(p.price)}</span> <span class="price-drop">${money(p.salePrice)}</span>`:money(p.price)} <span class="${statusClass(status)}"><i></i>${statusLabel(status)}</span></p></a><button class="quick-view-btn" type="button" onclick="openQuickView('${p.id}')">QUICK VIEW</button></article>`;
}
function renderProducts(el='#products',list=products()){ const node=$(el); if(node){ node.innerHTML=list.map(productCard).join(''); updateLikeButtons(); } }
function shopPage(){ const sel=$('#filter'); const url=new URL(location.href); const cat=url.searchParams.get('cat') || sel?.value || 'All'; if(sel) sel.value=cat; renderProducts('#products', products().filter(p=>cat==='All'||p.category===cat)); }
function renderHomeSections(){
  const ps=products();
  const trending=ps.filter(p=>(p.homeSection||p.section||'trending-now')==='trending-now' || (p.homeSection||'').toLowerCase().includes('trending'));
  const arrivals=ps.filter(p=>(p.homeSection||p.section||p.collection||'').toLowerCase().includes('new'));
  fillMarquee('#trendingMarquee', trending.length?trending:ps);
  fillMarquee('#newArrivalsMarquee', arrivals.length?arrivals:ps.slice().reverse());
}
function fillMarquee(sel,list){ const node=$(sel); if(!node)return; const html=list.concat(list).map(productCard).join(''); node.innerHTML=`<div class="marquee-track">${html}</div>`; updateLikeButtons(); }

function quickViewHTML(){ return `<div class="quick-modal" id="quickModal"><div class="quick-box"><button class="close" onclick="closeQuickView()">×</button><div id="quickContent"></div></div></div>`; }
function openQuickView(id){ const p=products().find(x=>String(x.id)===String(id)); if(!p)return; $('#quickContent').innerHTML=productDetailHTML(p,true); $('#quickModal').classList.add('show'); updateLikeButtons(); }
function closeQuickView(){ $('#quickModal')?.classList.remove('show'); }
function productPage(){ const id=new URL(location.href).searchParams.get('id'); const p=products().find(x=>String(x.id)===String(id)) || products()[0]; const d=$('#detail'); if(d) d.innerHTML=productDetailHTML(p,false); updateLikeButtons(); }
function productDetailHTML(p,quick=false){
  const status=productStatus(p); const disabled=status==='coming-soon'||status==='out-of-stock'; const sale=p.salePrice&&Number(p.salePrice)<Number(p.price); const outs=outSizesOf(p);
  const sizeBtns=sizesOf(p).map(s=>`<button type="button" class="size-option ${outs.includes(s)?'size-out':''}" ${outs.includes(s)?'disabled':''} onclick="selectSize(this)">${safe(s)}</button>`).join('');
  return `<div class="detail-media"><div class="detail-img" style="${imageStyle(productMainImage(p))}"></div></div><div class="detail-info"><p class="muted">${safe(p.category)}</p><div class="detail-title-row"><h1>${safe(p.name)}</h1>${likeButtonHTML(p.id,'product-like')}</div><p class="detail-price">${sale?`<span class="muted old-price">${money(p.price)}</span> <span class="price-drop">${money(p.salePrice)}</span>`:money(p.price)} <span class="${statusClass(status)}"><i></i>${statusLabel(status)}</span></p><p>${safe(p.desc||'A carefully selected Italian-made piece for a clean boutique wardrobe.')}</p><div class="size-picker product-sizes" data-product-id="${p.id}">${sizeBtns}</div><button class="btn add-cart-main ${disabled?'disabled':''}" ${disabled?'disabled':''} onclick="addToCart('${p.id}', selectedSize('${p.id}'))">${disabled?statusLabel(status).toUpperCase():'ADD TO CART'}</button>${disabled?'<button class="btn light notify-btn" onclick="toast(\'We will notify you when this product is available.\')">NOTIFY ME</button>':''}${quick?`<a class="btn light" href="product.html?id=${p.id}">VIEW FULL PRODUCT</a>`:''}</div>`;
}
function selectSize(btn){ $$('.size-option',btn.parentElement).forEach(b=>b.classList.remove('selected')); btn.classList.add('selected'); }
function selectedSize(id){ const holder=document.querySelector(`.product-sizes[data-product-id="${CSS.escape(String(id))}"]`); return holder?.querySelector('.size-option.selected')?.textContent.trim() || holder?.querySelector('.size-option:not(.size-out)')?.textContent.trim() || 'One Size'; }
function addToCart(id,size='One Size'){ const p=products().find(x=>String(x.id)===String(id)); if(!p)return; if(['coming-soon','out-of-stock'].includes(productStatus(p))){toast('This product is not available for cart.');return;} const found=cart.find(i=>String(i.id)===String(id)&&i.size===size); if(found) found.qty++; else cart.push({id:String(id),size,qty:1}); saveCart(); renderCartPanel(); toast('Added to cart'); }
function changeCartQty(index,delta){ if(!cart[index])return; cart[index].qty=Math.max(1,Number(cart[index].qty||1)+delta); saveCart(); renderCartPanel(); if($('#fullCart')) renderFullCart(); if($('#checkoutSummary')) renderCheckoutSummary(); }
function removeCartItem(index){ cart.splice(index,1); saveCart(); renderCartPanel(); if($('#fullCart')) renderFullCart(); }
function cartSubtotal(){ return cart.reduce((s,i)=>{const p=products().find(x=>String(x.id)===String(i.id)); return s+productPrice(p)*Number(i.qty||1);},0); }
function renderCartPanel(){ const box=$('#cartItems'); if(!box)return; if(!cart.length){box.innerHTML='<p class="muted">Your cart is empty.</p><button class="btn disabled" disabled>CHECKOUT</button>';return;} box.innerHTML=cart.map((i,idx)=>{const p=products().find(x=>String(x.id)===String(i.id)); if(!p)return''; return `<div class="cart-row"><span class="mini-img" style="${imageStyle(productMainImage(p))}"></span><div><b>${safe(p.name)}</b><br><small>${safe(i.size)}</small><div class="qty-control"><button onclick="changeCartQty(${idx},-1)">−</button><span>${i.qty}</span><button onclick="changeCartQty(${idx},1)">+</button></div></div><button class="remove-mini" onclick="removeCartItem(${idx})">×</button><b>${money(productPrice(p)*i.qty)}</b></div>`;}).join('')+`<p class="muted cart-fee-note">Additional fees will be calculated at checkout.</p><h3>Subtotal ${money(cartSubtotal())}</h3><a class="btn" href="checkout.html">CHECKOUT</a>`; }
function renderFullCart(){ const root=$('#fullCart'); if(!root)return; renderCartPanel(); root.innerHTML=$('#cartItems').innerHTML; }

function renderLoginPage(){
 const root=$('#loginRoot'); if(!root)return; if(currentUser){location.href='index.html';return;}
 root.innerHTML=`<div class="auth-hero"><img src="assets/logo-cropped.png" alt="Nita Style"><p class="eyebrow">Customer account</p><h1>Sign in or create your account</h1><p class="muted">Save your addresses, track orders, and receive your first-order code.</p></div><div class="auth-card card"><div class="auth-tabs"><button class="active" onclick="showAuth('signin')">SIGN IN</button><button onclick="showAuth('signup')">SIGN UP</button></div><div id="authForm"></div></div>`; showAuth('signin'); }
function showAuth(mode){ $$('.auth-tabs button').forEach((b,i)=>b.classList.toggle('active',(mode==='signin'?i===0:i===1))); const box=$('#authForm'); if(mode==='signin') box.innerHTML=`<input id="signEmail" class="field" placeholder="Email address"><input id="signPass" type="password" class="field" placeholder="Password"><button class="btn" onclick="signIn()">SIGN IN</button>`; else box.innerHTML=`<input id="suFirst" class="field" placeholder="First name"><input id="suLast" class="field" placeholder="Last name"><input id="suPhone" class="field" placeholder="Phone number"><input id="suEmail" type="email" class="field" placeholder="Email address"><input id="suPass" type="password" class="field" placeholder="Password"><button class="btn" onclick="startSignupVerification()">CONTINUE</button>`; }
async function sendEmail(payload){ try{ const res=await fetch('/.netlify/functions/send-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const json=await res.json().catch(()=>({})); if(!res.ok) throw new Error(json.error||'Email failed'); return json; }catch(e){ console.warn(e); return {ok:false,error:e.message}; } }
async function startSignupVerification(){ const first=$('#suFirst').value.trim(), last=$('#suLast').value.trim(), phone=$('#suPhone').value.trim(), email=normEmail($('#suEmail').value), pass=$('#suPass').value; if(!email||!first||!pass){toast('Please complete the sign-up form.');return;} const code=String(Math.floor(100000+Math.random()*900000)); verificationDraft={first,last,phone,email,password:pass,code,createdAt:Date.now()}; sessionStorage.setItem('nitaVerificationDraft',JSON.stringify(verificationDraft)); await sendEmail({type:'verification',to:email,code}); $('#authForm').innerHTML=`<div class="verify-step"><h2>One step left</h2><p class="muted">We sent a six-digit verification code to <b>${safe(email)}</b>. Check your inbox and enter it below.</p><input id="verifyCode" class="field" placeholder="6-digit code" maxlength="6"><button class="btn" onclick="finishSignupVerification()">VERIFY & CREATE ACCOUNT</button><button class="btn light" onclick="showAuth('signup')">BACK</button></div>`; }
async function finishSignupVerification(){ verificationDraft=verificationDraft||getJSON('nitaVerificationDraft',null); const code=$('#verifyCode').value.trim(); if(!verificationDraft||code!==verificationDraft.code){toast('Invalid verification code.');return;} const users=getUsers(); users[verificationDraft.email]={...users[verificationDraft.email],email:verificationDraft.email,first:verificationDraft.first,last:verificationDraft.last,phone:verificationDraft.phone,password:verificationDraft.password,addresses:users[verificationDraft.email]?.addresses||[],liked:users[verificationDraft.email]?.liked||[],createdAt:new Date().toISOString()}; await saveUsers(users); saveSession(users[verificationDraft.email]); await sendEmail({type:'discount',to:verificationDraft.email,code:'NITA10'}); sessionStorage.removeItem('nitaVerificationDraft'); location.href='index.html'; }
function signIn(){ const email=normEmail($('#signEmail').value), pass=$('#signPass').value; const u=getUsers()[email]; if(!u){toast('Account not found.');return;} if(u.password && u.password!==pass){toast('Wrong password.');return;} saveSession(u); location.href='index.html'; }

function renderAccount(){ const root=$('#accountRoot'); if(!root)return; if(!currentUser){location.href='login.html';return;} const users=getUsers(); const user=users[normEmail(currentUser.email)] || currentUser; currentUser=user; localStorage.setItem('nitaUser',JSON.stringify(user)); const userOrders=getOrders().filter(o=>normEmail(o.email)===normEmail(user.email)); const ongoing=userOrders.filter(o=>!['Delivered','Cancelled'].includes(o.status)); const previous=userOrders.filter(o=>['Delivered','Cancelled'].includes(o.status)); root.innerHTML=`<section class="account-head"><div><p class="eyebrow">My account</p><h1>Welcome ${safe(user.first||user.email)}</h1><p class="muted">Manage your profile, saved delivery addresses, and orders.</p></div></section><section class="account-grid"><div class="card"><h2>Personal information</h2><input id="accFirst" class="field" value="${safe(user.first||'')}" placeholder="First name"><input id="accLast" class="field" value="${safe(user.last||'')}" placeholder="Last name"><input class="field" value="${safe(user.email)}" disabled><input id="accPhone" class="field" value="${safe(user.phone||'')}" placeholder="Phone number"><button class="btn" onclick="saveAccountDetails()">SAVE DETAILS</button></div><div class="card"><h2>Saved delivery addresses</h2><div id="addressCards"></div><button class="btn light" onclick="showAddressForm()">ADD NEW ADDRESS</button><div id="addressFormWrap"></div></div></section><section class="card"><h2>Ongoing orders</h2>${ordersHTML(ongoing)}</section><section class="card"><h2>Previous orders</h2>${ordersHTML(previous)}</section><section class="card account-control"><h2>Account control</h2><p class="muted">Log out safely, or permanently remove your saved customer profile from this website.</p><button class="logout-red-outline" onclick="logout()">LOG OUT</button><button class="btn danger" onclick="deleteAccount()">DELETE ACCOUNT</button></section>`; renderAddressCards(); }
async function saveAccountDetails(){ const users=getUsers(); const email=normEmail(currentUser.email); users[email]={...users[email],...currentUser,first:$('#accFirst').value,last:$('#accLast').value,phone:$('#accPhone').value}; await saveUsers(users); saveSession(users[email]); toast('Account saved'); }
function addressList(){ const users=getUsers(); return users[normEmail(currentUser?.email)]?.addresses||[]; }
async function saveAddressList(list){ const users=getUsers(); const email=normEmail(currentUser.email); users[email]=users[email]||currentUser; users[email].addresses=list; await saveUsers(users); saveSession(users[email]); }
function renderAddressCards(selectMode=false){ const box=$('#addressCards')||$('#checkoutAddressArea'); if(!box)return; const list=addressList(); if(!list.length){ box.innerHTML='<p class="muted">No saved delivery address yet.</p>'; return;} box.innerHTML=list.map((a,i)=>`<div class="address-card" data-address-index="${i}"><div class="address-title" onclick="this.closest('.address-card').classList.toggle('open')">${selectMode?`<input type="radio" name="selectedAddress" value="${i}" ${i===0?'checked':''}>`:''}<b>${safe(a.label||'Address')}</b><small>${safe([a.city,a.street,a.building].filter(Boolean).join(' · '))}</small></div><div class="address-details"><p>${safe(a.city)} · ${safe(a.street)} · ${safe(a.building)} · Floor ${safe(a.floor)} · ${safe(a.apartment)}</p>${a.landmark?`<p>Landmark: ${safe(a.landmark)}</p>`:''}<button class="btn light" onclick="showAddressForm(${i})">EDIT</button></div></div>`).join(''); }
function showAddressForm(index=null){ const wrap=$('#addressFormWrap')||$('#checkoutNewAddressForm'); if(!wrap)return; const a=index!==null?addressList()[index]:{}; wrap.innerHTML=`<div class="address-form card"><input id="addrLabel" class="field" placeholder="Address name, for example Home or Office" value="${safe(a?.label||'')}"><input id="addrCity" class="field" placeholder="City" value="${safe(a?.city||'')}"><input id="addrStreet" class="field" placeholder="Street name" value="${safe(a?.street||'')}"><input id="addrBuilding" class="field" placeholder="Building name / number" value="${safe(a?.building||'')}"><input id="addrFloor" class="field" placeholder="Floor" value="${safe(a?.floor||'')}"><input id="addrApartment" class="field" placeholder="Apartment / door number" value="${safe(a?.apartment||'')}"><input id="addrLandmark" class="field" placeholder="Nearby landmark (optional)" value="${safe(a?.landmark||'')}"><textarea id="addrNotes" class="field" placeholder="Delivery notes (optional)">${safe(a?.notes||'')}</textarea><button class="btn" onclick="saveAddress(${index===null?'null':index})">SAVE DELIVERY ADDRESS</button></div>`; }
async function saveAddress(index=null){ const a={label:$('#addrLabel').value.trim()||'Address',city:$('#addrCity').value.trim(),street:$('#addrStreet').value.trim(),building:$('#addrBuilding').value.trim(),floor:$('#addrFloor').value.trim(),apartment:$('#addrApartment').value.trim(),landmark:$('#addrLandmark').value.trim(),notes:$('#addrNotes').value.trim()}; if(!a.city||!a.street||!a.building){toast('Please complete the required address fields.');return;} const list=addressList(); if(index===null||index===undefined) list.push(a); else list[index]=a; await saveAddressList(list); const wrap=$('#addressFormWrap')||$('#checkoutNewAddressForm'); if(wrap) wrap.innerHTML=''; if($('#accountRoot')) renderAddressCards(); if($('#checkoutAddressArea')) renderCheckoutAddressArea(); toast('Delivery address saved'); }
function ordersHTML(list){ if(!list.length)return '<p class="muted">No orders yet.</p>'; return list.map(o=>`<div class="order-card"><b>${safe(o.id)}</b><p class="muted">${safe(o.date)} · ${safe(o.payment||'Cash on Delivery')}</p><h3>${money(o.total)}</h3><span class="pill">${safe(o.status)}</span>${roadmapHTML(o.status)}<p class="muted">${(o.items||[]).map(i=>`${safe(i.name||i.id)} × ${i.qty}`).join(', ')}</p></div>`).join(''); }
function roadmapHTML(status){ const idx=Math.max(0,ORDER_STEPS.indexOf(status)); return `<div class="roadmap">${ORDER_STEPS.map((s,i)=>`<div class="road-step ${i<=idx?'done':''}"><i></i><span>${s}</span></div>`).join('')}</div>`; }
function logout(){ saveSession(null); location.href='index.html'; }
async function deleteAccount(){ if(!confirm('Delete your account?'))return; const users=getUsers(); delete users[normEmail(currentUser.email)]; await saveUsers(users); logout(); }

function nitaPremiumCheckoutInit(){ renderCheckoutAddressArea(); renderShippingBox(); prefillCheckoutContact(); renderCheckoutSummary(); }
function prefillCheckoutContact(){ if(!currentUser)return; const f=$('#checkoutForm'); if(!f)return; f.name.value=[currentUser.first,currentUser.last].filter(Boolean).join(' '); f.phone.value=currentUser.phone||''; f.email.value=currentUser.email||''; }
function renderCheckoutAddressArea(){ const area=$('#checkoutAddressArea'); if(!area)return; const list=addressList(); if(!list.length){ area.innerHTML='<p class="muted">No saved delivery address yet.</p><button type="button" class="btn light" onclick="showAddressForm()">ADD NEW DELIVERY ADDRESS</button><div id="checkoutNewAddressForm"></div>'; return; } area.innerHTML=`<div id="addressCards"></div><button type="button" class="btn light" onclick="showAddressForm()">ADD NEW DELIVERY ADDRESS</button><div id="checkoutNewAddressForm"></div>`; renderAddressCards(true); }
function renderShippingBox(){ const box=$('#shippingMethodBox'); if(box) box.innerHTML=`<div class="shipping-method"><b>Aramex delivery across Lebanon</b><span>${money(DELIVERY_FEE)}</span><small>$7 delivery fee for orders under $150 · 2–3 business days</small></div>`; }
function couponDiscount(code,email,subtotal){ code=String(code||'').trim().toUpperCase(); if(!code)return {discount:0,msg:''}; if(code==='NITA10'){ const uses=getDiscountUses(); if(uses[email]) return {discount:0,msg:'This first-order code was already used.'}; return {discount:subtotal*0.10,msg:`NITA10 applied: -${money(subtotal*.10)}`,kind:'NITA10'}; } const c=getCoupons().find(x=>String(x.code||'').toUpperCase()===code); if(!c)return {discount:0,msg:'Coupon code not found.'}; const now=new Date(); if(c.start&&now<new Date(c.start))return {discount:0,msg:'Coupon is not active yet.'}; if(c.end&&now>new Date(c.end+'T23:59:59'))return {discount:0,msg:'Coupon has expired.'}; if(c.oneTime&&c.usedEmails&&c.usedEmails[email])return {discount:0,msg:'This coupon was already used.'}; const disc=subtotal*Number(c.percent||0)/100; return {discount:disc,msg:`Coupon applied: -${money(disc)}`,kind:'admin',coupon:c}; }
function renderCheckoutSummary(){ const subtotal=cartSubtotal(); const email=normEmail($('#checkoutForm')?.email?.value || currentUser?.email); const code=$('#checkoutForm')?.coupon?.value || ''; const cd=couponDiscount(code,email,subtotal); const delivery=subtotal>=FREE_DELIVERY_MIN?0:DELIVERY_FEE; const total=Math.max(0,subtotal-cd.discount+delivery); const box=$('#checkoutSummary'); if(!box)return; box.innerHTML=(cart.length?cart.map(i=>{const p=products().find(x=>String(x.id)===String(i.id));return `<div class="summary-line"><span><b>${safe(p?.name||'Product')}</b><br><small>${safe(i.size)} × ${i.qty}</small></span><span>${money(productPrice(p)*i.qty)}</span></div>`}).join(''):'<p class="muted">Your cart is empty.</p>')+`<hr><div class="summary-line"><span>Subtotal</span><span>${money(subtotal)}</span></div>${cd.discount?`<div class="summary-line discount-good"><span>Discount</span><span>-${money(cd.discount)}</span></div>`:''}<div class="summary-line"><span>Aramex delivery</span><span>${delivery?money(delivery):'Free'}</span></div><div class="summary-total"><span>Total</span><span>${money(total)}</span></div>`; }
function applyCouponCode(){ renderCheckoutSummary(); toast(couponDiscount($('#checkoutForm')?.coupon?.value,normEmail($('#checkoutForm')?.email?.value||currentUser?.email),cartSubtotal()).msg || 'Enter a coupon code.'); }
async function placeOrder(){ const f=$('#checkoutForm'); if(!f)return; if(!cart.length){toast('Your cart is empty.');return;} const email=normEmail(f.email.value||currentUser?.email); const selected=Number((f.selectedAddress?.value ?? 0)); let address=addressList()[selected]; if(!address){toast('Please add or select a delivery address.');return;} const subtotal=cartSubtotal(); const cd=couponDiscount(f.coupon.value,email,subtotal); const delivery=subtotal>=FREE_DELIVERY_MIN?0:DELIVERY_FEE; const items=cart.map(i=>{const p=products().find(x=>String(x.id)===String(i.id));return {id:i.id,name:p?.name,price:productPrice(p),size:i.size,qty:i.qty,total:productPrice(p)*i.qty};}); const order={id:'NS'+Date.now(),date:new Date().toLocaleString(),customer:f.name.value,phone:f.phone.value,email,address,payment:'Cash on Delivery',status:'Order submitted',items,subtotal,discount:cd.discount,deliveryFee:delivery,total:subtotal-cd.discount+delivery}; const orders=getOrders(); orders.push(order); await saveOrders(orders); await reduceInventory(items); if(cd.kind==='NITA10'){const uses=getDiscountUses(); uses[email]=true; await saveDiscountUses(uses);} if(cd.kind==='admin'){const coupons=getCoupons(); const c=coupons.find(x=>x.code===cd.coupon.code); if(c&&c.oneTime){c.usedEmails=c.usedEmails||{};c.usedEmails[email]=true; await saveCoupons(coupons);}} await sendEmail({type:'order_confirmation',to:email,order}); await sendEmail({type:'admin_order',order}); sessionStorage.setItem('lastOrderId',order.id); cart=[]; saveCart(); location.href='order-success.html'; }
async function reduceInventory(items){ const ps=products(); items.forEach(i=>{const p=ps.find(x=>String(x.id)===String(i.id)); if(p&&p.quantity!==undefined){p.quantity=Math.max(0,Number(p.quantity||0)-Number(i.qty||1)); if(p.quantity===0)p.status='out-of-stock';}}); localStorage.setItem('nitaProducts',JSON.stringify(ps)); await saveProducts(ps); }
function renderOrderSuccess(){ const root=$('#orderSuccessRoot'); const order=getOrders().find(o=>o.id===sessionStorage.getItem('lastOrderId')) || getOrders().slice(-1)[0]; if(root) root.innerHTML=`<div class="success-card card"><div class="success-mark">✓</div><p class="eyebrow">Order received</p><h1>Thank you for your purchase</h1><p class="muted">Your Nita Style order has been submitted. You will receive an order confirmation by email when email sending is active.</p>${order?`<h3>${safe(order.id)}</h3><p>Total: ${money(order.total)}</p>`:''}<a class="btn" href="account.html">VIEW MY ACCOUNT</a><a class="btn light" href="shop.html">CONTINUE SHOPPING</a></div>`; }

async function renderAdmin(){ if(!isAdmin()){ document.body.innerHTML=headerHTML()+`<main class="page"><h1>Admin access required</h1><p class="muted">Sign in with an admin account.</p></main>`; return;} await refreshCloud(); const page=$('.admin-page'); if(page){ page.innerHTML=adminHTML(); renderAdminSection('orders'); } }
function adminHTML(){ return `<div class="admin-toolbar admin-hero"><div><p class="eyebrow">Nita Style Backend</p><h1>Admin Dashboard</h1><p class="muted">Choose one section at a time to manage orders, customers, products, coupons, and admin access.</p></div><a class="btn" href="shop.html">VIEW STORE</a></div><div class="admin-stats"><div class="card"><h3>Orders</h3><b>${getOrders().length}</b></div><div class="card"><h3>Customers</h3><b>${Object.keys(getUsers()).length}</b></div><div class="card"><h3>Products</h3><b>${products().length}</b></div></div><div class="admin-grid"><aside class="admin-side"><h3>Management</h3>${['orders','customers','products','add','coupons','admins'].map(s=>`<button class="admin-tab" onclick="renderAdminSection('${s}')">${s==='add'?'Add product':s}</button>`).join('')}</aside><section class="admin-layout"><div class="card" id="adminContent"></div></section></div>`; }
function setActiveAdminTab(name){ $$('.admin-tab').forEach(b=>b.classList.toggle('active', b.textContent.toLowerCase().includes(name==='add'?'add':name))); }
function renderAdminSection(name){ setActiveAdminTab(name); const box=$('#adminContent'); if(!box)return; if(name==='orders') return renderAdminOrders(box); if(name==='customers') return renderAdminCustomers(box); if(name==='products') return renderAdminProducts(box); if(name==='add') return renderAddProduct(box); if(name==='coupons') return renderCoupons(box); if(name==='admins') return renderAdmins(box); }
function renderAdminOrders(box){ const orders=getOrders(); box.innerHTML=`<div class="admin-toolbar"><h2>Orders</h2><span class="pill">${orders.length} total</span></div>`+(orders.length?orders.map((o,i)=>`<div class="admin-row"><div><b>${safe(o.id)}</b><p>${safe(o.customer)} · ${safe(o.email)} · ${safe(o.phone)}</p><p><b>${money(o.total)}</b> · ${safe(o.status)}</p></div><select onchange="adminUpdateOrder('${o.id}',this.value)">${ORDER_STEPS.concat(['Cancelled']).map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="btn danger" onclick="adminDeleteOrder('${o.id}')">DELETE</button></div>`).join(''):'<p class="muted">No orders yet.</p>'); }
async function adminUpdateOrder(id,status){ if(!confirm('Update this order status?'))return; const orders=getOrders(); const o=orders.find(x=>x.id===id); if(!o)return; o.status=status; await saveOrders(orders); await sendEmail({type:'order_status',to:o.email,order:o}); renderAdminSection('orders'); }
async function adminDeleteOrder(id){ if(!confirm('Delete this order from admin records?'))return; await saveOrders(getOrders().filter(o=>o.id!==id)); renderAdminSection('orders'); }
function renderAdminCustomers(box){ const users=getUsers(); const admins=getAdminEmails(); box.innerHTML=`<div class="admin-toolbar"><h2>Signed-up customers</h2><span class="pill">${Object.keys(users).length} total</span></div>`+Object.values(users).map(u=>`<div class="admin-row"><div><b>${safe([u.first,u.last].filter(Boolean).join(' ')||u.email)}</b><p>${safe(u.email)} · ${safe(u.phone||'')}</p><p>${admins.includes(normEmail(u.email))?'Admin access':'Customer'}</p></div><button class="btn light" onclick="adminEditCustomer('${safe(u.email)}')">EDIT</button><button class="btn light" onclick="toggleAdminUser('${safe(u.email)}')">${admins.includes(normEmail(u.email))?'REMOVE ADMIN':'MAKE ADMIN'}</button><button class="btn danger" onclick="adminDeleteCustomer('${safe(u.email)}')">DELETE</button></div>`).join('') || '<p class="muted">No customers yet.</p>'; }
function adminEditCustomer(email){ const u=getUsers()[normEmail(email)]; if(!u)return; const box=$('#adminContent'); box.innerHTML=`<h2>Edit customer</h2><input id="cuFirst" class="field" value="${safe(u.first||'')}"><input id="cuLast" class="field" value="${safe(u.last||'')}"><input class="field" value="${safe(u.email)}" disabled><input id="cuPhone" class="field" value="${safe(u.phone||'')}"><button class="btn" onclick="adminSaveCustomer('${safe(u.email)}')">SAVE CUSTOMER</button><button class="btn light" onclick="renderAdminSection('customers')">BACK</button>`; }
async function adminSaveCustomer(email){ const users=getUsers(); const u=users[normEmail(email)]; u.first=$('#cuFirst').value; u.last=$('#cuLast').value; u.phone=$('#cuPhone').value; await saveUsers(users); renderAdminSection('customers'); }
async function adminDeleteCustomer(email){ if(NITA_OWNER_EMAILS.includes(normEmail(email))){toast('Owner admin cannot be deleted.');return;} if(!confirm('Delete this customer account?'))return; const users=getUsers(); delete users[normEmail(email)]; await saveUsers(users); renderAdminSection('customers'); }
async function toggleAdminUser(email){ const e=normEmail(email); let admins=getAdminEmails(); if(NITA_OWNER_EMAILS.includes(e)){toast('Owner admin cannot be removed.'); return;} admins=admins.includes(e)?admins.filter(x=>x!==e):[...admins,e]; await saveAdminEmails(admins); renderAdminSection('customers'); }
function renderAdmins(box){ const users=Object.values(getUsers()); const admins=getAdminEmails(); box.innerHTML=`<h2>Admin access</h2><p class="muted">Choose which signed-up customers can access the admin dashboard.</p>`+users.map(u=>`<label class="admin-toggle"><input type="checkbox" ${admins.includes(normEmail(u.email))?'checked':''} onchange="toggleAdminUser('${safe(u.email)}')"> ${safe(u.email)}</label>`).join(''); }
function renderAddProduct(box){ box.innerHTML=`<h2>Add product</h2><div class="admin-form"><input id="pname" class="field" placeholder="Product name"><input id="pprice" class="field" type="number" placeholder="Price"><input id="psale" class="field" type="number" placeholder="Sale price optional"><input id="pqty" class="field" type="number" placeholder="Quantity"><select id="pstatus" class="field"><option value="in-stock">In stock</option><option value="coming-soon">Coming soon</option><option value="out-of-stock">Out of stock</option></select><select id="pcat" class="field">${ADMIN_CATEGORIES.map(c=>`<option>${c}</option>`)}</select><select id="phome" class="field"><option value="trending-now">Trending Now</option><option value="new-arrivals">New Arrivals</option></select><select id="pcolor" class="field"><option>Black</option><option>White</option><option>Beige</option><option>Multi-color</option></select><textarea id="pdesc" class="field" placeholder="Description"></textarea><input id="pphotos" type="file" class="field" multiple accept="image/*" onchange="readAdminPhotos(event)"><div id="photoPreview"></div><div class="size-picker">${PRODUCT_SIZES.map(s=>`<label><input type="checkbox" class="admin-size" value="${s}"> ${s}</label>`).join('')}</div></div><button class="btn" onclick="addProductAdmin()">ADD PRODUCT</button>`; }
window.pendingAdminPhotos=[];
function readAdminPhotos(e){ window.pendingAdminPhotos=[]; const files=Array.from(e.target.files||[]); Promise.all(files.map(f=>new Promise(r=>{const fr=new FileReader(); fr.onload=()=>r(fr.result); fr.readAsDataURL(f);}))).then(arr=>{window.pendingAdminPhotos=arr; $('#photoPreview').innerHTML=arr.map(x=>`<img src="${x}" style="width:70px;height:90px;object-fit:cover;margin:4px">`).join('');}); }
async function addProductAdmin(){ const qty=Number($('#pqty')?.value||0); const p={id:'p'+Date.now(),name:$('#pname').value,price:Number($('#pprice').value||0),salePrice:$('#psale').value?Number($('#psale').value):'',category:$('#pcat').value,collection:$('#phome').value==='new-arrivals'?'New Arrivals':'Trending Now',homeSection:$('#phome').value,status:$('#pstatus').value,quantity:qty,initialQuantity:qty,color:$('#pcolor').value,desc:$('#pdesc').value,sizes:$$('.admin-size:checked').map(x=>x.value),outOfStockSizes:[],photos:window.pendingAdminPhotos,img:window.pendingAdminPhotos[0]||'linear-gradient(135deg,#fafafa,#ddd)'}; const ps=products(); ps.push(p); await saveProducts(ps); await refreshCloud(); renderAdmin(); }
function renderAdminProducts(box){ const ps=products(); box.innerHTML=`<div class="admin-toolbar"><h2>Edit listed products</h2><span class="pill">${ps.length} live</span></div>`+ps.map(p=>`<div class="admin-row"><span class="mini-img" style="${imageStyle(productMainImage(p))}"></span><div><b>${safe(p.name)}</b><p>${safe(p.category)} · ${money(productPrice(p))} · ${statusLabel(productStatus(p))}</p></div><button class="btn light" onclick="editProduct('${p.id}')">EDIT</button><button class="btn danger" onclick="removeProduct('${p.id}')">REMOVE</button></div>`).join(''); }
function editProduct(id){ const p=products().find(x=>String(x.id)===String(id)); const box=$('#adminContent'); if(!p||!box)return; box.innerHTML=`<h2>Edit product</h2><input id="eName" class="field" value="${safe(p.name)}"><input id="ePrice" class="field" type="number" value="${p.price}"><input id="eSale" class="field" type="number" value="${p.salePrice||''}"><input id="eQty" class="field" type="number" value="${p.quantity||0}"><select id="eStatus" class="field"><option value="in-stock">In stock</option><option value="coming-soon">Coming soon</option><option value="out-of-stock">Out of stock</option></select><select id="eCat" class="field">${ADMIN_CATEGORIES.map(c=>`<option ${p.category===c?'selected':''}>${c}</option>`)}</select><select id="eHome" class="field"><option value="trending-now" ${p.homeSection==='trending-now'?'selected':''}>Trending Now</option><option value="new-arrivals" ${p.homeSection==='new-arrivals'?'selected':''}>New Arrivals</option></select><textarea id="eDesc" class="field">${safe(p.desc||'')}</textarea><h4>Available sizes</h4>${PRODUCT_SIZES.map(s=>`<label><input type="checkbox" class="edit-size" value="${s}" ${sizesOf(p).includes(s)?'checked':''}> ${s}</label>`).join('')}<h4>Out-of-stock sizes</h4>${PRODUCT_SIZES.map(s=>`<label><input type="checkbox" class="edit-out-size" value="${s}" ${outSizesOf(p).includes(s)?'checked':''}> ${s}</label>`).join('')}<button class="btn" onclick="saveProductEdit('${p.id}')">SAVE PRODUCT</button><button class="btn light" onclick="renderAdminSection('products')">BACK</button>`; $('#eStatus').value=p.status||'in-stock'; }
async function saveProductEdit(id){ const ps=products(); const p=ps.find(x=>String(x.id)===String(id)); p.name=$('#eName').value;p.price=Number($('#ePrice').value);p.salePrice=$('#eSale').value?Number($('#eSale').value):'';p.quantity=Number($('#eQty').value);p.status=$('#eStatus').value;p.category=$('#eCat').value;p.homeSection=$('#eHome').value;p.collection=p.homeSection==='new-arrivals'?'New Arrivals':'Trending Now';p.desc=$('#eDesc').value;p.sizes=$$('.edit-size:checked').map(x=>x.value);p.outOfStockSizes=$$('.edit-out-size:checked').map(x=>x.value); await saveProducts(ps); renderAdminSection('products'); }
async function removeProduct(id){ if(!confirm('Remove product?'))return; await saveProducts(products().filter(p=>String(p.id)!==String(id))); renderAdminSection('products'); }
function renderCoupons(box){ const cs=getCoupons(); box.innerHTML=`<h2>Coupon codes</h2><div class="coupon-builder"><input id="couponCode" class="field" placeholder="Code"><input id="couponPercent" class="field" type="number" placeholder="Discount %"><input id="couponStart" class="field" type="date"><input id="couponEnd" class="field" type="date"><label><input id="couponOneTime" type="checkbox" checked> One-time use</label><button class="btn" onclick="addCouponAdmin()">CREATE COUPON</button></div>`+cs.map(c=>`<div class="admin-row"><b>${safe(c.code)}</b><span>${c.percent}%</span><button class="btn danger" onclick="deleteCoupon('${safe(c.code)}')">DELETE</button></div>`).join(''); }
async function addCouponAdmin(){ const cs=getCoupons(); cs.push({code:$('#couponCode').value.trim().toUpperCase(),percent:Number($('#couponPercent').value||0),start:$('#couponStart').value,end:$('#couponEnd').value,oneTime:$('#couponOneTime').checked,usedEmails:{},active:true}); await saveCoupons(cs); renderAdminSection('coupons'); }
async function deleteCoupon(code){ await saveCoupons(getCoupons().filter(c=>c.code!==code)); renderAdminSection('coupons'); }

function renderLikedPage(){ const root=$('#likedPageRoot'); if(!root)return; const liked=getLikedIds(); const ps=products().filter(p=>liked.includes(String(p.id))); root.innerHTML=`<p class="eyebrow">Saved pieces</p><h1>Liked items</h1>${ps.length?`<div class="grid">${ps.map(productCard).join('')}</div>`:'<p class="muted">No liked items yet.</p>'}`; updateLikeButtons(); }

window.addEventListener('storage',()=>{ loadSession(); loadCart(); updateHeaderCounts(); updateCartCount(); });
